# appveyor.yml for Windows
build: off

clone_folder: c:\gopath\src\github.com\iwdgo\testinghello

environment:
  GOPATH: c:\gopath

stack: go 1.12

before_test:
  - go vet ./...

test_script:
  - go test ./...
